agent:
    main_agent: "TrainingAgnet"
    criterion_agent: "MSELoss"
    model_agent: "GDN"

train:
    resume: False
    random_seed: 1234
    device: "cuda"
    ngpu: 1
    epochs: 50

    bn_track_running_stats: True
    bn_momentum: 0.1

model:
    input_dim: 5
    embedding_dim: 64
    out_layer_num: 1
    out_layer_inter_dim: 256

    topk: 30

criterion:

dataset:
    dataset: "wadi"
    dataset_path: "./data/SWaT_interval_10/"
    classes: 0
    input_size: 0

    batch_size: 64
    num_workers: 4
    train_portion: 0.9

    slide_win: 5
    slide_stride: 1

optim:
    optimizer: "adam"
    lr: 0.00005
    weight_decay: 0.0
    momentum: 0.9
    alpha: 0.9
    beta: 0.99

    scheduler: "cosine"
    decay_step: 10
    decay_ratio: 0.1

logs_path:
    logger_path: "./logs/"
    writer_path: "./logs/tb/"

experiment_path:
    resume_path: "./best_checkpoint.pth"
    checkpoint_root_path: "./checkpoints/"
    best_checkpoint_path: "./best_checkpoint.pth"

    lookup_table_path: "./lookup_table.json"
    searched_model_path: "./searched_model_architecture.npy"



